name: Precommit
description: Runs production build, lint, and all tests on the code base.
runs:
  using: "composite"
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Run Install
        run: |
          corepack enable
          yarn install

      - name: Build
        run: yarn run build:prod

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test:ci
