name: Post Push

on:
  push:
    branches:
      - main

jobs:
  post-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
        corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        run: yarn run build:prod

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test:ci
