on:
  workflow_call

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Run Install
        run: |
          corepack enable
          yarn install

      - name: Build
        run: yarn run build:prod

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test:ci
