on:
  pull_request:
    branches:
      - main

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Precommit
        uses: ./.github/actions/precommit
